Add proof of concept  of using DotNetBrowser with Unity
TeamDev-IP/DotNetBrowser-Examples pull request #128
Opened 2022-10-27 10:52 UTC by evhenii-komar

This proof of concept shows how to use DotNetBrowser in a simple 3d scene and how to implement it as a menu and chat in the Fps Microgame project of Unity tutorial.

2022-10-27 11:49 UTC, anna-dolbina commented on README.md
> +* Integration with Unity3D: [C#](csharp/unity3d/DotNetBrowser_Unity)
```suggestion
* Integration with Unity3D: [C#](csharp/unity3d)
```
In this case, anyone who follows this link will see the README.

2022-10-27 13:26 UTC, anna-dolbina commented on README.md
> +* Integration with Unity3D: [C#](csharp/unity3d)
```suggestion
* Integrate with Unity3D: [C#](csharp/unity3d)
```
Let's make this entry look similar to the other entries in this section.

2022-10-27 15:50 UTC, roman-vasylenko commented on csharp/unity3d/README.md
> +As you can see, there are amounts of fields where we bind regarding scene objects. You can see in `PlaneScript` code how we use this attached objects. The one field is common for every primitive scri
> there are amounts of fields where we bind regarding scene objects

It is not clear what is meant here.

2022-10-27 16:10 UTC, roman-vasylenko commented
Suggested edit:
```diff
diff --git a/csharp/unity3d/README.md b/csharp/unity3d/README.md
index e59f9949..070bb1e3 100644
--- a/csharp/unity3d/README.md
+++ b/csharp/unity3d/README.md
@@ -5,7 +5,7 @@
 This example project has two scenes that demonstrate how to use DotNetBrowser with Unity3D to show the browser in the 3D scene on surfaces of geometry primitives.
 
 1. "DnbSimple" folder contains content for "DotNetBrowserScene.unity" scene, where you can see how to use a browser on base geometry primitives in the simplest way.
-2. "DnbFps" folder contains content for the Unity "[Fps Microgame](https://learn.unity.com/project/fps-template)" project. You can see how the browser could be implemented in this tutorial here.
+2. "DnbFps" folder contains content for the Unity "[Fps Microgame](https://learn.unity.com/project/fps-template)" project. It demonstrates in-game browser integration.
 
 ### How to run
 

```

2022-10-27 16:13 UTC, roman-vasylenko commented
Suggested edit:
```diff
diff --git a/csharp/unity3d/README.md b/csharp/unity3d/README.md
index e59f9949..6795c1ac 100644
--- a/csharp/unity3d/README.md
+++ b/csharp/unity3d/README.md
@@ -9,9 +9,9 @@ This example project has two scenes that demonstrate how to use DotNetBrowser wi
 
 ### How to run
 
-The folder of the Unity3D project is **DotNetBrowser_Unity**. It should be selected in **[Unity Hub](https://unity.com/unity-hub)** as **[Unity3D](https://unity3d.com)** project to open.
+The folder of the Unity3D project is **DotNetBrowser_Unity**. It should be selected in [**Unity Hub**](https://unity.com/unity-hub) as [**Unity3D**](https://unity3d.com) project to open.
   
-Please note that this project uses a dedicated local package to automate pulling and updating DotNetBrowser libraries. You can see it referenced in _DotNetBrowser_Unity\Packages\packages-lock.json_ and _DotNetBrowser_Unity\Packages\manifest.json_ as "**com.teamdev.dotnetbrowser.deps**" package. The package source code is located in a **Dependencies** folder. 
+Please note that this project uses a dedicated local package to automate pulling and updating DotNetBrowser libraries. You can see it referenced in _DotNetBrowser_Unity\Packages\packages-lock.json_ and _DotNetBrowser_Unity\Packages\manifest.json_ as **com.teamdev.dotnetbrowser.deps** package. The package source code is located in a **Dependencies** folder. 
 
 The package will check and download the latest version of **DotNetBrowser** libraries on loading the Unity project. The same check is performed on recompiling the Unity project scripts.
 
@@ -23,12 +23,12 @@ The main idea consists of four classes located in _DotNetBrowser_Unity\Assets\Dn
 3. `MouseHelper` - contains logic that is used to redirect mouse input.
 4. `KeyboardHelper` - contains logic that is used to redirect keyboard input.
 
-You can use `BrowserViewScript` directly if you need to display the web page and perform input handling on a static mesh. But it will look better to bring some action to the scene and a bit of classic browser UI. `CubeScript`, `PlaneScript` and `SphereScript` are `BrowserViewScript` subclasses that add a some additional behavior directly to according primitives. `PlaneScript` has a little bit of classic browser UI. It allows typing a URL and navigate back and forward. `SphereScript` and `CubeScript` just add a simple rotation to bring some action to the scene.
+You can use `BrowserViewScript` directly if you need to display the web page and perform input handling on a static mesh. But it will look better to bring some action to the scene and a bit of classic browser UI. `CubeScript`, `PlaneScript` and `SphereScript` are `BrowserViewScript` subclasses that add a some additional behavior directly to according primitives. `PlaneScript` has a little bit of classic browser UI. It allows typing a URL and performing back/forward navigation. `SphereScript` and `CubeScript` just add a simple rotation to bring some action to the scene.
 
 ### Scene content
 Both examples have their own content. However, _DnbSimple_ has the base content and _DnbFps_ uses it as a basement.
 
-#### "_DnbSimple_" and "_DotNetBrowserScene.unity_".
+#### DnbSimple and DotNetBrowserScene.unity
 The scene objects are geometry primitives, UI elements, and empty objects for `BrowserScript`(s):
 
 ![image](https://user-images.githubusercontent.com/85240195/196160746-ef5e6c03-d9c6-4078-9498-0540e70d2fe7.png)
@@ -37,7 +37,7 @@ The "**Browser 0**" and "**Browser 1**" are empty objects where we attach `Brows
   
 ![image](https://user-images.githubusercontent.com/85240195/196161142-102da254-2679-4a2c-8c23-7dd767afc024.png)
   
-**Primitives** are primitives with standard material to show HTML pages. It is **Plane**, **Cube** and **Sphere**. They have according script component in **Inspector** panel, it is `PlaneScript`, `CubeScript` and `SphereScript` accordingly.
+**Primitives** are primitives with standard material to show HTML pages. It is **Plane**, **Cube** and **Sphere**. They have the corresponding script component in **Inspector** panel. It is `PlaneScript`, `CubeScript` and `SphereScript` accordingly.
 Here is how the attached `CubeScript` looks, for example:
   
 ![image](https://user-images.githubusercontent.com/85240195/166907252-2d9eff6a-7d6d-4e4a-a8e0-0e6de4eb42af.png)
@@ -54,13 +54,13 @@ This field is set to the empty scene object that has attached `BrowserScript`. I
 
 Also, you can see an **EventSystem** and **Canvas** with UI elements in the scene tree. The UI elements are bound to `PlaneScript`(see the `PlaneScript` component picture above). And there are default **Main Camera** and **Directional Light** objects for the normal rendering process.
 
-#### "_DnbFps_" and "_MainScene_".
+#### DnbFps and MainScene
 DnbFps is a Unity Fps Microgame with an implemented custom HTML menu and a design concept of the game chat. It has subclasses `MenuBrowserScript` and `MenuViewScript` that extend `BrowserViewScript` and allow it to affect the game from the HTML page of the menu.
 
 Necessary scene objects are geometry primitives, UI elements, and empty objects for `BrowserScript` and `MenuBrowserScript`:
 ![image](https://user-images.githubusercontent.com/85240195/196393367-821b32a7-063c-48d6-9e1c-cf815471e4fd.png)
 
-The "ChatBrowser" and "MenuBrowser" are empty objects where we attach _BrowserScript_ and _MenuBrowserScript_ respectively. They are empty because they don't require a visualization, they are needed to control the browser lifecycle in the attached script. Also, you can see "_Html UI Manager_" object there which we use to assign "_Html UI Manager_" script where we handle a Tab key.
+The "ChatBrowser" and "MenuBrowser" are empty objects where we attach `BrowserScript` and `MenuBrowserScript` respectively. They are empty because they don't require a visualization and needed to control the browser lifecycle in the attached script. Also, you can see _Html UI Manager_ object there which we use to assign _Html UI Manager_ script where we handle a Tab key.
 
 To show the menu and the chat, we use the Raw Image elements of Canvas:
 
@@ -70,5 +70,5 @@ There are two fields for `MenuViewScript`:
 
 ![image](https://user-images.githubusercontent.com/85240195/196397478-d4b329fb-577f-435f-b03f-d51080b1b090.png)
 
-The "_Browser Game Object_" is an object that has attached `BrowserScript`. In this way, we specify what browser will be shown by this Raw Image element.
-The "_Menu Manager Game Object_" is an object that has `HtmlUIManager` script attached. This script controls the activation and deactivation of the menu.
+The "Browser Game Object" is an object that has attached `BrowserScript`. In this way, we specify what browser will be shown by this Raw Image element.
+The "Menu Manager Game Object" is an object that has `HtmlUIManager` script attached. This script controls the activation and deactivation of the menu.

```

2022-10-28 09:32 UTC, evhenii-komar commented on csharp/unity3d/README.md
> +As you can see, there are amounts of fields where we bind regarding scene objects. You can see in `PlaneScript` code how we use this attached objects. The one field is common for every primitive scri
I've rephrased it.

2022-10-28 12:30 UTC, anna-dolbina commented on csharp/unity3d/DotNetBrowser_Unity/Assets/DnbSimple/Scripts/BrowserScript.cs
> +                RenderingMode = RenderingMode.OffScreen
Please add the code that demonstrates how to configure the DotNetBrowser license. In addition, it is necessary to describe this in the README for this example.

2022-11-02 11:40 UTC, evhenii-komar commented on csharp/unity3d/DotNetBrowser_Unity/Assets/DnbSimple/Scripts/BrowserScript.cs
> +                RenderingMode = RenderingMode.OffScreen
Done.

2022-11-02 12:47 UTC, anna-dolbina commented on csharp/unity3d/README.md
> +```
Let's add a relative reference that points to this block of the code and shows where to find it. Something like "DotNetBrowser_Unity/Assets/DnbSimple/Scripts/BrowserScript.cs#L80-L84"

Note: you can view and check the links in the README at https://github.com/TeamDev-IP/DotNetBrowser-Examples/tree/unity-proof-of-concept/csharp/unity3d

2022-11-07 10:50 UTC, evhenii-komar commented on csharp/unity3d/README.md
> +```
Done.

2022-11-07 10:54 UTC, anna-dolbina commented on csharp/unity3d/README.md
> +You must have a license key to make it work. You can use a [_dotnetbrowser.license_](https://dotnetbrowser-support.teamdev.com/docs/guides/installation/license.html#installing-license:~:text=working%
Please replace absolute repository-related links with the relative ones. For example:
```suggestion
You must have a license key to make it work. You can use a [_dotnetbrowser.license_](https://dotnetbrowser-support.teamdev.com/docs/guides/installation/license.html#installing-license:~:text=working%20directory.-,Installing%20key%20through%20a%20license%20file,-The%20license%20file) file and put it in the [Editor](DotNetBrowser_Unity/Assets/Editor) directory of your project. It will be copied to the directory with executables after the building automatically. Or, you can set the license through the code by setting it in `EngineOptions` in the `BrowserScript` class. It looks like [this](DotNetBrowser_Unity/Assets/DnbSimple/Scripts/BrowserScript.cs#L82):
```

2022-11-07 10:55 UTC, anna-dolbina commented on csharp/unity3d/README.md
> +The main idea consists of four classes located in _DotNetBrowser_Unity\Assets\DnbSimple\Scripts\\_:
```suggestion
The main idea consists of four classes located in [the Scripts folder](DotNetBrowser_Unity/Assets/DnbSimple/Scripts/):
```

2022-11-07 10:59 UTC, anna-dolbina requested changes
Please correct the links in `README.md`

2022-11-08 08:44 UTC, anna-dolbina commented on csharp/unity3d/README.md
> +More details how to install the license is in the [documentation](https://dotnetbrowser-support.teamdev.com/docs/guides/installation/license.html#installing-license).
Please move this paragraph to the "How it works" section.

2022-11-08 08:46 UTC, anna-dolbina commented on csharp/unity3d/README.md
> +2. "DnbFps" folder contains content for the modified Unity "[Fps Microgame](https://learn.unity.com/project/fps-template)" project. It is a base for the first-person shooter where DotNetBrowser rende
```suggestion
2. "DnbFps" folder contains content for the modified Unity "[FPS Microgame](https://learn.unity.com/project/fps-template)" project. It is a base for the first-person shooter where DotNetBrowser renders the menu and concept of the game chat.
```

2022-11-08 08:47 UTC, anna-dolbina commented on csharp/unity3d/README.md
> +DnbFps is a Unity Fps Microgame with an implemented custom HTML menu and a design concept of the game chat. It has subclasses `MenuBrowserScript` and `MenuViewScript` that extend `BrowserViewScript`
```suggestion
DnbFps is a [Unity FPS Microgame](https://learn.unity.com/project/fps-template) with an implemented custom HTML menu and a design concept of the game chat. It has subclasses `MenuBrowserScript` and `MenuViewScript` that extend `BrowserViewScript` and allow it to affect the game from the HTML page of the menu.
```

2022-11-08 09:53 UTC, evhenii-komar commented on csharp/unity3d/README.md
> +More details how to install the license is in the [documentation](https://dotnetbrowser-support.teamdev.com/docs/guides/installation/license.html#installing-license).
I moved it to the "How to run" section.

2022-11-08 10:01 UTC, anna-dolbina approved these changes

2022-11-08 10:34 UTC, merged