Update part of examples written in CSharp
TeamDev-IP/DotNetBrowser-Examples pull request #90
Opened 2022-01-13 10:58 UTC by eugene-yakush

This PR removes unnecessary console output and exception handling in the following samples:

- ChromiumBinariesResolver.Wpf
- ContextMenu.SpellCheck.WinForms
- ContextMenu.SpellCheck.Wpf
- ContextMenu.WinForms
- ContextMenu.Wpf
- CreateHtmlUi.Wpf
- CustomShortcuts.WinForms
- Dom.DragAndDrop.WinForms
- DragAndDrop.Wpf
- JavaScriptBridge.WinForms
- KeyboardEventSimulation.WinForms
- KeyboardEventSimulation.Wpf
- Kiosk.Wpf
- MailToHandling.WinForms
- TransparentWebPage.Wpf
- UiAutomation.Wpf
- Zoom.Wpf

2022-01-13 11:43 UTC, vladislav-tsvek requested changes
Please take a look at the comments.

2022-01-13 11:43 UTC, vladislav-tsvek commented on csharp/DragAndDrop.Wpf/MainWindow.xaml.cs
> +            sb.AppendLine($"\nEvent name:{name}");
It is necessary to add the space after colons in this file.
For ex.:
```suggestion
            sb.AppendLine($"\nEvent name: {name}");
```

2022-01-13 11:43 UTC, vladislav-tsvek commented on csharp/KeyboardEventSimulation.Wpf/MainWindow.xaml.cs
> +                                                      .Build());
```suggestion
                     {
                         RenderingMode = RenderingMode.OffScreen
                     }.Build());
```

2022-01-13 11:43 UTC, vladislav-tsvek commented on csharp/Kiosk.Wpf/MainWindow.xaml.cs
> +                                                      .Build());
```suggestion
                     {
                         RenderingMode = RenderingMode.HardwareAccelerated
                     }.Build());
```

2022-01-13 11:43 UTC, vladislav-tsvek commented on csharp/ChromiumBinariesResolver.Wpf/MainWindow.xaml.cs
>      public partial class MainWindow : INotifyPropertyChanged
```suggestion
    /// <summary>
    ///     This example demonstrates how to deploy Chromium binaries
    ///     over network.
    /// </summary>
    public partial class MainWindow : INotifyPropertyChanged
```

2022-01-20 09:38 UTC, vladislav-tsvek approved these changes
LGTM

2022-01-20 11:12 UTC, anna-dolbina approved these changes

2022-01-20 12:41 UTC, merged